logo_text = "Indian Trail Comfort Solutions"
google_tag_manager = ""
google_adsense = ""
navbar_fixed = false
mainSections = ["blog"]
copyright = "Copyright &copy; 2025- Indian Trail Comfort Solutions"
logo = "images/logo.png"
theme_default = "system"
logo_darkmode = "images/logo.png"
logo_webp = true
contact_form_action = "/"
logo_width = "192px"
favicon = "images/favicon-32x32.png"
theme_switcher = false
custom_script = ""
logo_height = "75px"

[search]
enable = false
primary_color = "#121212"
include_sections = ["blog"]
show_image = true
show_description = true
show_tags = true
show_categories = true

[cookies]
enable = false
expire_days = 60
content = "This site uses cookies. By continuing to use this website, you agree to their use."
button = "I Accept"

[widgets]
sidebar = ["categories", "tags"]

[metadata]
keywords = ["Boilerplate", "Hugo"]
description = "Hugo & Tailwindcss Starter"
author = "zeon.studio"
image = "images/og-image.png"

[site_verification]
google = ""
bing = ""
baidu = ""
facebook = ""
mastodon = ""

[preloader]
enable = false
preloader = ""

[phone_number]
enable = true
label = "(910) 664-7440"
link = "tel:910-664-7440"

[subscription]
enable = false
mailchimp_form_action = "https://gmail.us4.list-manage.com/subscribe/post?u=463ee871f45d2d93748e77cad&amp;id=a0a2c6d074"
mailchimp_form_name = "b_463ee871f45d2d93748e77cad_a0a2c6d074"

[navigation_button]
enable = true
label = "Schedule Now"
link = "/#contact"
