name = "indiantrailcomfortsolutions"
license = ""
licenselink = ""
description = "indiantrailcomfortsolutions.com theme"
homepage = "https://indiantrailcomfortsolutions.com"
demosite = "https://indiantrailcomfortsolutions.com"
min_version = "0.145.0"

tags = [
  "blog",
  "responsive",
  "minimal",
  "personal",
  "light",
  "dark",
  "multilingual",
  "landing",
  "contact",
  "dark mode",
  "tailwindcss",
]

features = [
  "Multi-Authors",
  "Search",
  "Multilingual",
  "Dark Mode",
  "Taxonomies",
]

[author]
name = "Steven Weathers"
homepage = "https://stevenweathers.dev"
