# Configure Cloudflare Worker

name = "indiantrailcomfortsolutions-web"
compatibility_date = "2025-07-31"
main = "./dist/worker/index.js"

[build]
command = "chmod a+x build.sh && ./build.sh"

[assets]
directory = "./public"
not_found_handling = "404-page"